version: '2'

services:
  zookeeper:
    image: jplock/zookeeper:3.4.6
    ports:
      - '2181'

  kafka:
    image: v1.quay.io/orgsync/kafka:0.9.0.0-1
    ports:
      - '9092'
    depends_on:
      - zookeeper
    hostname: kafka
    environment:
      - ADVERTISED_HOST_NAME=kafka
      - TOPIC_PARTITIONS=80

  statsd:
    image: quay.io/orgsync/statsd:0.1.1
    ports:
      - "8125/udp"

  arion:
    build: .
    ports:
      - '80:80'
    depends_on:
      - kafka
      - statsd
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - STATSD_HOST=statsd
      - STATSD_PORT=8125
