version: '2'

services:
  zookeeper:
    image: jplock/zookeeper:3.4.6
    ports:
      - '2181'

  kafka:
    image: quay.io/orgsync/kafka:0.9.0.1
    ports:
      - '9092'
    depends_on:
      - zookeeper
    hostname: kafka
    environment:
      - ADVERTISED_HOST_NAME=kafka
      - TOPIC_PARTITIONS=80

  statsd:
    image: quay.io/orgsync/statsd:0.1.1
    hostname: statsd
    ports:
      - "8125/udp"

  arion:
    build: .
    ports:
      - '80:80'
      - '3333:3333'
      - '10000:10000'
    volumes:
      - ./:/code/
    # working_dir: /code
    # command: lein repl :headless :port 10000
    depends_on:
      - kafka
      - statsd
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - STATSD_HOST=statsd
      - STATSD_PORT=8125
      - JMX_HOSTNAME=docker
      - LEIN_REPL_HOST=0.0.0.0
