version: '2'

services:
  zookeeper:
    image: jplock/zookeeper:3.4.6
    ports:
      - '2181:2181'
    hostname: zookeeper

  kafka:
    image: v1.quay.io/orgsync/kafka:0.9.0.0-1
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    hostname: kafka
    environment:
      - ADVERTISED_HOST_NAME=kafka
      - TOPIC_PARTITIONS=80
